apiVersion: v2
name: sd-customer-billing
description: "BIAN Service Domain: Customer Billing (Process pattern, Operations and Execution)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - process
annotations:
  bian/business-area: "Operations and Execution"
  bian/business-domain: "Account Management"
  bian/asset-type: "Customer Bill"
  bian/control-record: "Customer Bill Procedure"
